name: CI/CD Pipeline for AWS ECR and Hugging Face

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[s3]

      - name: Run DVC & Tests
        env:
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          dvc repro
          python -m unittest discover -s tests -p "*.py"

      # AWS login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # Hugging Face login
      - name: Login to Hugging Face Docker Registry
        run: |
          echo "${{ secrets.HF_TOKEN }}" | docker login -u "RamanSinghIITD" --password-stdin registry.huggingface.co

      # Build once, push to both
      - name: Build & Push Docker Images
        env:
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          IMAGE_NAME=${{ secrets.ECR_REPOSITORY }}
          AWS_IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
          HF_IMAGE=registry.huggingface.co/ramansinghiitd/sentiment-analysis:latest

          docker build --build-arg CAPSTONE_TEST=$CAPSTONE_TEST -t $IMAGE_NAME:latest .
          
          # Tag for AWS ECR
          docker tag $IMAGE_NAME:latest $AWS_IMAGE
          docker push $AWS_IMAGE
          
          # Tag for Hugging Face
          docker tag $IMAGE_NAME:latest $HF_IMAGE
          docker push $HF_IMAGE
